name: Bridge Petroleum
favicon: null
layout_spectrum: 0.5082338531501591
typography_spectrum: 0.4555010227486491
title: placeholder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8492ac'
    - '#e3a806'
    - '#050b17'
    - '#543b1d'
  brandStrength: 0.6265437935944647
  lightness: 0.6620196050498635
  saturation: 0.3537052692845464
  rhythmicContrast: 0.37024400825612247
purpose: []
